[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
command = "npm run build"
publish = ".output/public"
functions = "myfunctions"
node_bundler = "esbuild"

[build.environment]
NODE_VERSION = "20"
